package main.fmwk.core.verifications;

public enum VerificationStrategy {

    PAGE_TITLE, LOCATOR_VISIBLE, CONTAINS_TEXT, CONTAINS_TEXT_ARR, CONTAINS_TEXT_PATTERN, CONTAINS_TEXT_PATTERN_ARR,
    ATTRIBUTE, CLASS, COUNT, NAME, CSS, ID, MATCHES_TEXT, HAS_VALUE, HAS_VALUES, IS_CHECKED, IS_EDITABLE, IS_DISABLED,
    IS_EMPTY, IS_FOCUSED, HAS_JS_PROPERTY
}
